version: '3'
services:



  discovery:
    image: sanogotech/service-registry
    container_name: service-registry
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

#   cassandra-node-1:
#     hostname: cassandra-1
#     image: cassandra:latest
#     command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
#     expose:
#       - 7000
#       - 7001
#       - 7199
#       - 9042
#       - 9160
#  cassandra-node-2:
#    hostname: cassandra-2
#    image: cassandra:latest
#    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
#    links:
#      - cassandra-node-1:cassandra
#    expose:
#      - 7000
#      - 7001
#      - 7199
#      - 9042
#      - 9160
  gateway:
    image: sanogotech/service-gateway
    container_name: service-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  # accounts:
    # image: sanogotech/service-accounts-api
    # container_name: service-accounts
    # build:
      # context: ./containerized-accounts
      # dockerfile: Dockerfile
    # ports:
      # - "7500:2222"
    # depends_on:
      # - discovery
     #- cassandra-node-1
    # links:
      # - discovery:discovery

  # products:
    # image: sanogotech/service-products-api
    # container_name: service-products
    # build:
      # context: ./containerized-products
      # dockerfile: Dockerfile
    # ports:
      # - "7501:2222"
    # depends_on:
      # - discovery
      # - accounts
    # links:
      # - discovery:discovery

  # orders:
    # image: sanogotech/service-orders-api
    # container_name: service-orders
    # build:
      # context: ./containerized-orders
      # dockerfile: Dockerfile
    # ports:
      # - "7502:2222"
    # depends_on:
      # - discovery
      # - products
    # links:
      # - discovery:discovery

  # main:
    # image: sanogotech/service-main-api
    # container_name: service-main
    # build:
      # context: ./containerized-main
      # dockerfile: Dockerfile
    # ports:
      # - "7503:2222"
    # depends_on:
      # - discovery
      # - orders
    # links:
      # - discovery:discovery
      # - accounts:accounts
      # - products:products
      # - orders:orders
